import axios from 'axios';
import { SALES_DRAFTS_ROUTE } from '../utils/salesRoutes';
const client = axios.create({ baseURL: process.env.REACT_APP_NETWORK });
export function salesDraftsApi(token, orgId) {
  const headers = { Authorization: `Bearer ${token}`, 'X-Active-Org': String(orgId) };
  return {
    allocationContext: signal => client.get('/sales/draft-allocations/context', { headers, signal }),
    allocateDraft: (body, signal) => client.post('/sales/draft-allocations', body, { headers, signal }),
    list: (page, limit, signal, filters = {}) => client.get(SALES_DRAFTS_ROUTE, { headers,
      params: { page, limit, ...(filters.branch_id ? { branch_id: filters.branch_id } : {}),
        ...(filters.search ? { search: filters.search } : {}) }, signal }),
    read: (key, signal) => client.get(`${SALES_DRAFTS_ROUTE}/${encodeURIComponent(key)}`, { headers, signal }),
    pricingPreview: (key, signal) => client.get(`${SALES_DRAFTS_ROUTE}/${encodeURIComponent(key)}/pricing-preview`, { headers, signal }),
    latestPricingSnapshot: (key, draftVersion, signal) => client.get(`${SALES_DRAFTS_ROUTE}/${encodeURIComponent(key)}/pricing-snapshots/latest`, { headers, params: { draft_version: draftVersion }, signal }),
    preparePricingSnapshot: (key, body, signal) => client.post(`${SALES_DRAFTS_ROUTE}/${encodeURIComponent(key)}/pricing-snapshots`, body, { headers, signal }),
    postingOptions: (key, draftVersion, signal) => client.get(`/sales/posting-options/${encodeURIComponent(key)}`, { headers, params: { draft_version: draftVersion }, signal }),
    createPostingAttempt: (key, body, signal) => client.put(`/sales/posting-attempts/${encodeURIComponent(key)}`, body, { headers, signal }),
    readPostingAttempt: (key, signal) => client.get(`/sales/posting-attempts/${encodeURIComponent(key)}`, { headers, signal }),
    recordCardConfirmation: (attemptKey, confirmationKey, body, signal) => client.post(`/sales/posting-attempts/${encodeURIComponent(attemptKey)}/card-confirmations/${encodeURIComponent(confirmationKey)}`, body, { headers, signal }),
    finalizePostingAttempt: (key, body, signal) => client.post(`/sales/posting-attempts/${encodeURIComponent(key)}/finalize`, body, { headers, signal }),
    readInvoice: (key, signal) => client.get(`/sales/invoices/${encodeURIComponent(key)}`, { headers, signal }),
    postedInvoice: (key, draftVersion, signal) => client.get(`${SALES_DRAFTS_ROUTE}/${encodeURIComponent(key)}/posted-invoice`, { headers, params: { draft_version: draftVersion }, signal }),
    collectionOptions: (key, signal) => client.get(`/sales/invoices/${encodeURIComponent(key)}/collection-options`, { headers, signal }),
    createCollection: (key, body, signal) => client.put(`/sales/collections/${encodeURIComponent(key)}`, body, { headers, signal }),
    readCollection: (key, signal) => client.get(`/sales/collections/${encodeURIComponent(key)}`, { headers, signal }),
    invoiceCollections: (key, signal) => client.get(`/sales/invoices/${encodeURIComponent(key)}/collections`, { headers, signal }),
    returnOptions: (key, signal) => client.get(`/sales/invoices/${encodeURIComponent(key)}/return-options`, { headers, signal }),
    invoiceReturnClaims: (key, page, limit, signal) => client.get(`/sales/invoices/${encodeURIComponent(key)}/returns`, { headers, params: { page, limit }, signal }),
    createReturnClaim: (key, body, signal) => client.put(`/sales/returns/${encodeURIComponent(key)}`, body, { headers, signal }),
    readReturnClaim: (key, signal) => client.get(`/sales/returns/${encodeURIComponent(key)}`, { headers, signal }),
    reviewReturnClaim: (key, body, signal) => client.post(`/sales/returns/${encodeURIComponent(key)}/review`, body, { headers, signal }),
    returnProcessingOptions: (key, signal) => client.get(`/sales/returns/${encodeURIComponent(key)}/processing-options`, { headers, signal }),
    createReturnCreditNote: (returnKey, body, signal) => client.put(`/sales/returns/${encodeURIComponent(returnKey)}/credit-note`, body, { headers, signal }),
    invoiceCreditNotes: (key, page, limit, signal) => client.get(`/sales/invoices/${encodeURIComponent(key)}/credit-notes`, { headers, params: { page, limit }, signal }),
    readCreditNote: (key, signal) => client.get(`/sales/credit-notes/${encodeURIComponent(key)}`, { headers, signal }),
    stockConditionSources: (page, limit, signal, invoiceKey, creditNoteKey) => client.get('/inventory/stock-condition-cases/sources', { headers,
      params: { page, limit, ...(invoiceKey ? { invoice_key: invoiceKey } : {}), ...(creditNoteKey ? { credit_note_key: creditNoteKey } : {}) }, signal }),
    stockConditionCases: (page, limit, signal, view = 'ALL', creditNoteLineId) => client.get('/inventory/stock-condition-cases', { headers,
      params: { page, limit, view, ...(creditNoteLineId ? { credit_note_line_id: creditNoteLineId } : {}) }, signal }),
    requestStockCondition: (body, signal) => client.post('/inventory/stock-condition-cases', body, { headers, signal }),
    reviewStockCondition: (key, body, signal) => client.post(`/inventory/stock-condition-cases/${encodeURIComponent(key)}/review`, body, { headers, signal }),
    executeStockCondition: (key, body, signal) => client.post(`/inventory/stock-condition-cases/${encodeURIComponent(key)}/execute`, body, { headers, signal }),
    invoicePrintOptions: (key, signal) => client.get(`/sales/invoices/${encodeURIComponent(key)}/print-options`, { headers, signal }),
    invoicePrintJobs: (key, page, limit, signal) => client.get(`/sales/invoices/${encodeURIComponent(key)}/print-jobs`, { headers, params: { page, limit }, signal }),
    createInvoicePrintJob: (invoiceKey, jobKey, body, signal) => client.put(`/sales/invoices/${encodeURIComponent(invoiceKey)}/print-jobs/${encodeURIComponent(jobKey)}`, body, { headers, signal }),
    handoffInvoicePrint: (jobKey, body, signal) => client.post(`/sales/print-jobs/${encodeURIComponent(jobKey)}/handoff`, body, { headers, signal, responseType: 'blob' }),
    resolveInvoicePrint: (jobKey, body, signal) => client.post(`/sales/print-jobs/${encodeURIComponent(jobKey)}/resolve`, body, { headers, signal }),
    requestFloorCase: (body, signal) => client.post('/sales/pricing/floor-cases', body, { headers, signal }),
    floorCases: (page, limit, signal, view = 'ALL') => client.get('/sales/pricing/floor-cases', { headers, params: { page, limit, view }, signal }),
    reviewFloorCase: (key, body, signal) => client.post(`/sales/pricing/floor-cases/${encodeURIComponent(key)}/review`, body, { headers, signal }),
    history: (key, page, limit, signal) => client.get(`${SALES_DRAFTS_ROUTE}/${encodeURIComponent(key)}/history`, { headers, params: { page, limit }, signal }),
    revision: (key, version, signal) => client.get(`${SALES_DRAFTS_ROUTE}/${encodeURIComponent(key)}/history/${version}`, { headers, signal }),
    save: (key, body, signal) => client.put(`${SALES_DRAFTS_ROUTE}/${encodeURIComponent(key)}`, body, { headers, signal }),
    branches: (page, limit, signal) => client.get('/sales/draft-sources/branches', { headers, params: { page, limit }, signal }),
    products: (page, limit, signal, search = '') => client.get('/sales/draft-sources/products', { headers, params: { page, limit, search }, signal }),
    releaseCases: (page, limit, signal, view) => client.get('/inventory/reservation-release-cases', { headers, params: { page, limit, view }, signal }),
    reviewRelease: (key, body, signal) => client.post(`/inventory/reservation-release-cases/${encodeURIComponent(key)}/review`, body, { headers, signal }),
    executeRelease: (key, body, signal) => client.post(`/inventory/reservation-release-cases/${encodeURIComponent(key)}/execute`, body, { headers, signal }),
    reservations: (key, page, limit, signal) => client.get(`/inventory/reservation-release-cases/sources/${encodeURIComponent(key)}`, { headers, params: { page, limit }, signal }),
    requestRelease: (body, signal) => client.post('/inventory/reservation-release-cases', body, { headers, signal }),
    reallocationCases: (page, limit, signal, view) => client.get('/inventory/reservation-reallocation-cases', { headers, params: { page, limit, view }, signal }),
    reviewReallocation: (key, body, signal) => client.post(`/inventory/reservation-reallocation-cases/${encodeURIComponent(key)}/review`, body, { headers, signal }),
    reallocationExecutionContext: (key, signal) => client.get(`/inventory/reservation-reallocation-cases/${encodeURIComponent(key)}/execution-context`, { headers, signal }),
    executeReallocation: (key, body, signal) => client.post(`/inventory/reservation-reallocation-cases/${encodeURIComponent(key)}/execute`, body, { headers, signal }),
    requestReallocation: (body, signal) => client.post('/inventory/reservation-reallocation-cases', body, { headers, signal }),
    otherStoreCases: (page, limit, signal, view) => client.get('/inventory/other-store-fulfilment-cases', { headers, params: { page, limit, view }, signal }),
    reviewOtherStore: (key, body, signal) => client.post(`/inventory/other-store-fulfilment-cases/${encodeURIComponent(key)}/review`, body, { headers, signal }),
    otherStoreExecutionContext: (key, signal) => client.get(`/inventory/other-store-fulfilment-cases/${encodeURIComponent(key)}/execution-context`, { headers, signal }),
    executeOtherStore: (key, body, signal) => client.post(`/inventory/other-store-fulfilment-cases/${encodeURIComponent(key)}/execute`, body, { headers, signal }),
    requestOtherStore: (body, signal) => client.post('/inventory/other-store-fulfilment-cases', body, { headers, signal }),
    workingStore: (signal) => client.get('/inventory/other-store-fulfilment-cases/working-store', { headers, signal }),
    requestDeadline: (body, signal) => client.post('/inventory/reservation-deadline-cases', body, { headers, signal }),
    deadlineCases: (page, limit, signal, view) => client.get('/inventory/reservation-deadline-cases', { headers, params: { page, limit, view }, signal }),
    reviewDeadline: (key, body, signal) => client.post(`/inventory/reservation-deadline-cases/${encodeURIComponent(key)}/review`, body, { headers, signal }),
    scheduleDeadline: (key, body, signal) => client.post(`/inventory/reservation-deadline-cases/${encodeURIComponent(key)}/schedule`, body, { headers, signal }),
    dueReservations: (page, limit, signal) => client.get('/inventory/reservation-deadline-cases/due', { headers, params: { page, limit }, signal }),
  };
}
