export const MOCK_ORDERS = [
  {
    id: 101,
    po_number: "NCE-PO#26102",
    po_nce: "NPO#26-0594",
    company: "WEICHANG ALUMINIUM",
    goods_description: "ALUMINIUM PROFILE FOR SELMA SITE",
    status: "UNDER_PRODUCTION",
    status_label: "Manufacturing",
    sheet_type: "NOBLE",
    year: 2026,
    urgent_action: false,
    order_mail_date: "2026-07-17",
    quote_sent_date: "2026-07-22",
    quote_received_date: "2026-07-27",
    pi_confirmed_date: "2026-08-12",
    payment_date: "2026-08-13",
    balance_payment_date: null,
    eta_date: "2026-09-15",
    freight_type: "Sea Freight",
    remark: "PIP & Under Production",
    org_name: "Noblecon",
    consignee: "NOBLECON ENTERPRISE",
  },
  {
    id: 102,
    po_number: "NCE-PO#26106",
    po_nce: "NPO#26-0598",
    company: "INDIAN OCEAN COMMODITY TRADING FZC",
    goods_description: "REBAR STEEL T16 & T12",
    status: "UNDER_PRODUCTION",
    status_label: "Manufacturing",
    sheet_type: "NOBLE",
    year: 2026,
    urgent_action: true,
    order_mail_date: "2026-07-20",
    quote_sent_date: "2026-07-22",
    quote_received_date: "2026-07-22",
    pi_confirmed_date: "2026-07-27",
    payment_date: null,
    balance_payment_date: null,
    eta_date: "2026-09-08",
    freight_type: "Sea Freight",
    remark: "Urgent shipment required for Perseverance site",
    org_name: "Noblecon",
    consignee: "NOBLECON ENTERPRISE",
  },
  {
    id: 103,
    po_number: "SHJ-PO#26044",
    po_nce: "SPO#26-0112",
    company: "SAHAJANAND TRADING PTY",
    goods_description: "CERAMIC FLOOR TILES & ADHESIVE",
    status: "PI_CONFIRMED",
    status_label: "Confirm-Quote / PI",
    sheet_type: "SAHAJANAND",
    year: 2026,
    urgent_action: false,
    order_mail_date: "2026-07-28",
    quote_sent_date: "2026-07-28",
    quote_received_date: "2026-07-31",
    pi_confirmed_date: "2026-08-12",
    payment_date: "2026-08-15",
    balance_payment_date: null,
    eta_date: "2026-09-22",
    freight_type: "Sea Freight",
    remark: "PI confirmed and ready for production",
    org_name: "Sahajanand",
    consignee: "SAHAJANAND",
  },
  {
    id: 104,
    po_number: "SAHAJ#250609",
    po_nce: "NPO#25-403",
    company: "AL RABIH GENERAL TRADING",
    goods_description: "WELDMESH MESH FABRIC",
    status: "RECEIVED",
    status_label: "Received",
    sheet_type: "SAHAJ",
    year: 2025,
    urgent_action: false,
    order_mail_date: "2025-06-09",
    quote_sent_date: "2025-06-10",
    quote_received_date: "2025-06-11",
    pi_confirmed_date: "2025-06-26",
    payment_date: "2025-07-02",
    balance_payment_date: "2025-07-10",
    eta_date: "2025-07-15",
    freight_type: "Sea Way",
    remark: "Received at Providence Warehouse",
    org_name: "Sahaj Construction",
    consignee: "SAHAJ CONSTRUCTION",
  },
  {
    id: 105,
    po_number: "SAHAJ#250405",
    po_nce: "NPO#25-363",
    company: "VISAKA INDUSTRIES",
    goods_description: "CEMENT BOARD 6MM & 9MM",
    status: "READY_TO_LOAD",
    status_label: "Ready to Load",
    sheet_type: "SAHAJ",
    year: 2025,
    urgent_action: true,
    order_mail_date: "2025-04-05",
    quote_sent_date: "2025-04-05",
    quote_received_date: "2025-04-07",
    pi_confirmed_date: "2025-04-07",
    payment_date: "2025-04-10",
    balance_payment_date: null,
    eta_date: "2025-05-18",
    freight_type: "Sea Way",
    remark: "Waiting container booking at Mundra port",
    org_name: "Sahaj Construction",
    consignee: "SAHAJ CONSTRUCTION",
  },
  {
    id: 106,
    po_number: "NCE-PO#26119",
    po_nce: "NPO#26-0608",
    company: "ZHEJIANG DOUBLE-LIN VALVES CO., LTD",
    goods_description: "COPPER & BRASS FITTINGS",
    status: "QUOTE_SENT",
    status_label: "Asked for Quote",
    sheet_type: "NOBLE",
    year: 2026,
    urgent_action: false,
    order_mail_date: "2026-07-31",
    quote_sent_date: "2026-07-31",
    quote_received_date: null,
    pi_confirmed_date: null,
    payment_date: null,
    balance_payment_date: null,
    eta_date: "2026-10-05",
    freight_type: "Sea Freight",
    remark: "Waiting for quotation response",
    org_name: "Noblecon",
    consignee: "NOBLECON ENTERPRISE",
  },
  {
    id: 107,
    po_number: "SHJ-PO#26052",
    po_nce: "SPO#26-0120",
    company: "CHAOZHOU YUEJIE TECHNOLOGY CO LTD",
    goods_description: "TOILET & BATHROOM FIXTURES",
    status: "PENDING",
    status_label: "Request (Pending)",
    sheet_type: "SAHAJANAND",
    year: 2026,
    urgent_action: true,
    order_mail_date: "2026-08-05",
    quote_sent_date: null,
    quote_received_date: null,
    pi_confirmed_date: null,
    payment_date: null,
    balance_payment_date: null,
    eta_date: "2026-10-20",
    freight_type: "Sea Freight",
    remark: "Pending specification confirmation from site engineer",
    org_name: "Sahajanand",
    consignee: "SAHAJANAND",
  },
];

export const STATUS_PIPELINE = [
  {
    key: "PENDING",
    label: "Request (Pending)",
    shortLabel: "Request",
    progress: 10,
    color: "bg-slate-500",
    badgeColor: "bg-slate-100 text-slate-700 border-slate-300 dark:bg-slate-800 dark:text-slate-300 dark:border-slate-700"
  },
  {
    key: "QUOTE_SENT",
    label: "Asked for Quote",
    shortLabel: "Asked for Quote",
    progress: 20,
    color: "bg-blue-500",
    badgeColor: "bg-blue-50 text-blue-800 border-blue-200 dark:bg-blue-950/60 dark:text-blue-300 dark:border-blue-800"
  },
  {
    key: "QUOTE_RECEIVED",
    label: "Received Quote",
    shortLabel: "Received Quote",
    progress: 35,
    color: "bg-indigo-500",
    badgeColor: "bg-indigo-50 text-indigo-800 border-indigo-200 dark:bg-indigo-950/60 dark:text-indigo-300 dark:border-indigo-800"
  },
  {
    key: "PI_CONFIRMED",
    label: "Confirm-Quote / PI",
    shortLabel: "Confirm-Quote / PI",
    progress: 50,
    color: "bg-purple-500",
    badgeColor: "bg-purple-50 text-purple-800 border-purple-200 dark:bg-purple-950/60 dark:text-purple-300 dark:border-purple-800"
  },
  {
    key: "UNDER_PRODUCTION",
    label: "Manufacturing",
    shortLabel: "Manufacturing",
    progress: 70,
    color: "bg-orange-500",
    badgeColor: "bg-orange-50 text-orange-800 border-orange-200 dark:bg-orange-950/60 dark:text-orange-300 dark:border-orange-800"
  },
  {
    key: "READY_TO_LOAD",
    label: "Ready to Load",
    shortLabel: "Ready to Load",
    progress: 85,
    color: "bg-lime-500",
    badgeColor: "bg-lime-50 text-lime-800 border-lime-200 dark:bg-lime-950/60 dark:text-lime-300 dark:border-lime-800"
  },
  {
    key: "SEA_WAY",
    label: "Sea Way (In Transit)",
    shortLabel: "Sea Way (In Transit)",
    progress: 92,
    color: "bg-cyan-500",
    badgeColor: "bg-cyan-50 text-cyan-800 border-cyan-200 dark:bg-cyan-950/60 dark:text-cyan-300 dark:border-cyan-800"
  },
  {
    key: "RECEIVED",
    label: "Received",
    shortLabel: "Received",
    progress: 100,
    color: "bg-emerald-500",
    badgeColor: "bg-emerald-50 text-emerald-800 border-emerald-200 dark:bg-emerald-950/60 dark:text-emerald-300 dark:border-emerald-800"
  },
];

export function getVisibleStages() {
  return STATUS_PIPELINE;
}
